StudentFileShare6/Models/CourseViewModel.cs
namespace StudentFileShare6.Models
{
    public class CourseViewModel
    {
        public string SchoolName { get; set; }
        public string CourseName { get; set; }

        public string CourseID { get; set; }

        public List<Document> Documents { get; set; }
    }
}

StudentFileShare6/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentFileShare6.Models;
using NPinyin;
using Microsoft.CodeAnalysis;
using StudentFileShare6.data;

namespace StudentFileShare6.Controllers
{
    public class CourseController : Controller
    {
        private readonly CourseContext _context;
        private readonly DocumentContext _docContext;

        public CourseController(CourseContext context, DocumentContext docContext)
        {
            _context = context;
            _docContext= docContext;
        }

        // GET: Course
        public async Task<IActionResult> Index()
        {
            var courseContext = _context.Course.Include(c => c.Universities);
            return View(await courseContext.ToListAsync());
        }

        // GET: Course/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Universities)
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Course/Create
        public IActionResult Create()
        {
            //ViewData["SchoolID"] = new SelectList(_context.Set<University>(), "SchoolID", "Name");
            //return View();
            var course = new Course();
            return View(course);

        }

        // POST: Course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,CourseName,SchoolID")] Course course)
        {
            if (!ModelState.IsValid)
            {
                // Log validation errors
                foreach (var modelStateEntry in ModelState.Values)
                {
                    foreach (var error in modelStateEntry.Errors)
                    {
                        System.Diagnostics.Debug.WriteLine(error.ErrorMessage);
                        //if the ModelState is not valid, it will print the error message in Output's Debug area
                    }
                }

                return View(course);
            }

            if (ModelState.IsValid)
            {

                // Convert Chinese characters to Pinyin for Name
                String NameInCharacters = course.CourseName ;    //in Chinese characters
                course.CourseName = Pinyin.GetPinyin(course.CourseName);

               


                course.GenerateRandomCourseID(_context);

                //set name back to Chinese characters
                course.CourseName = NameInCharacters;
             


                _context.Add(course);
                await _context.SaveChangesAsync();
             //   return RedirectToAction(nameof(Index));
                return RedirectToAction("CourseCreateSuccess", "Course");   //redirect to "CourseCreateSuccess" action of "Course" controller
            }
            ViewData["SchoolID"] = new SelectList(_context.Set<University>(), "SchoolID", "SchoolID", course.SchoolID);
            return View(course);
        }

        // GET: Course/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["SchoolID"] = new SelectList(_context.Set<University>(), "SchoolID", "SchoolID", course.SchoolID);
            return View(course);
        }

        // POST: Course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CourseID,CourseName,SchoolID")] Course course)
        {
            if (id != course.CourseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SchoolID"] = new SelectList(_context.Set<University>(), "SchoolID", "SchoolID", course.SchoolID);
            return View(course);
        }

        // GET: Course/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Universities)
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'CourseContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(string id)
        {
          return (_context.Course?.Any(e => e.CourseID == id)).GetValueOrDefault();
        }

        public async Task<IActionResult> CourseCreateSuccess()
        {
           //after upload complete we show this
            return View();
        }

        public async Task<IActionResult> CourseView(string schoolName, string courseName, string courseID)
        {
            //to have own page for each course with a website template showing schoolName, courseName
            //example link:  https://localhost:7192/Course/CourseView?schoolName=ABCSchool&courseName=Mathematics&CourseID=A123

            var documentsOfTheCourse = await _docContext.Document.Where(d => d.CourseID == courseID).ToListAsync();

            var model = new CourseViewModel
            {
                SchoolName = schoolName,
                CourseName = courseName,
                CourseID = courseID,
                Documents = documentsOfTheCourse
            };

            return View(model);
        }

    }
}

StudentFileShare6/Controllers/UserSavedInfoController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentFileShare6.data;
using StudentFileShare6.Models;
using System.Linq;
using System.Threading.Tasks;

namespace StudentFileShare6.Controllers
{
    public class UserSavedInfoController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly UserSavedInfoContext _context;
        private readonly CourseContext _courseContext;
        private readonly UniversityContext _universityContext;
        private readonly DocumentContext _documentContext;

        public UserSavedInfoController(UserManager<IdentityUser> userManager, UserSavedInfoContext context, CourseContext courseContext, UniversityContext universityContext, DocumentContext documentContext)
        {
            _userManager = userManager;
            _context = context;
            _courseContext = courseContext;
            _universityContext = universityContext;
            _documentContext = documentContext;
        }

        public async Task<IActionResult> UserSaved()
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            var userSavedInfo = await _context.UserSavedInfo
                .Where(u => u.UserId == userId)
                .Include(u => u.Course)
                .Include(u => u.Document)
                .Include(u => u.University)
                .ToListAsync();


         


            return View(userSavedInfo);
        }



        [HttpGet]
        public async Task<IActionResult> IsCourseFavorited(string courseId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the course is already saved by the user
            var existingSavedCourse = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.CourseID == courseId)
                .FirstOrDefaultAsync();

            if (existingSavedCourse != null)
            {
                // var isFavorited = true;
                return Json(new { isFavorited = true });
            }

            return Json(new { isFavorited = false });
        }

        [HttpPost]
        public async Task<IActionResult> SaveCourse(string courseId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the course is already saved by the user
            var existingSavedCourse = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.CourseID == courseId)
                .FirstOrDefaultAsync();

            if (existingSavedCourse != null)
            {
                // Course is already saved, so remove it
                _context.UserSavedInfo.Remove(existingSavedCourse);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "课程已移除收藏" ,isFavorited = false }); // course removed from saved
            }

            var courseToSave = await _courseContext.Course
                .Include(d => d.Universities)
                
                .Where(c => c.CourseID == courseId)
                .FirstOrDefaultAsync();

            if (courseToSave == null)
            {
                // Course not found
                return Json(new { success = false,  message = "找不到课程" });
            }

            var userSavedInfo = new UserSavedInfo
            {
                UserId = userId,
                CourseID = courseToSave.CourseID,
                CourseName = courseToSave.CourseName,
                SchoolName = courseToSave.Universities.Name
            };

            _context.UserSavedInfo.Add(userSavedInfo);
            await _context.SaveChangesAsync();

            return Json(new { success = false, message = "课程收藏成功" , isFavorited = true});
        }



        [HttpGet]
        public async Task<IActionResult> IsUniversityFavorited(string universityId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the course is already saved by the user
            var existingSavedUniversity = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.SchoolID == universityId)
                .FirstOrDefaultAsync();

            if (existingSavedUniversity != null)
            {
                // var isFavorited = true;
                return Json(new { isFavorited = true });
            }

            return Json(new { isFavorited = false });
        }


        [HttpPost]
        public async Task<IActionResult> SaveUniversity(string universityId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the course is already saved by the user
            var existingSavedUniversity = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.SchoolID == universityId)
                .FirstOrDefaultAsync();

            if (existingSavedUniversity != null)
            {
                // University is already saved, so remove it
                _context.UserSavedInfo.Remove(existingSavedUniversity);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "大学已移除收藏",isFavorited = false }); // university removed from saved
            }

            var universityToSave = await _universityContext.Universities
              
                .Where(c => c.SchoolID == universityId)
                .FirstOrDefaultAsync();

            if (universityToSave == null)
            {
                // Course not found
                return Json(new { success = false, message = "未找到大学" });
            }

            var userSavedInfo = new UserSavedInfo
            {
                UserId = userId,
                SchoolID = universityToSave.SchoolID,
                SchoolName = universityToSave.Name
            };

            _context.UserSavedInfo.Add(userSavedInfo);
            await _context.SaveChangesAsync();

            return Json(new { success = false, message = "大学收藏成功", isFavorited = true });
        }


        [HttpGet]
        public async Task<IActionResult> IsDocumentFavorited(string documentId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the document is already saved by the user
            var existingSavedDocument = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.DocumentID == documentId)
                .FirstOrDefaultAsync();

            if (existingSavedDocument != null)
            {
               // var isFavorited = true;
                return Json(new { isFavorited = true });
            }

            return Json(new { isFavorited = false });
        }


        [HttpPost]
        public async Task<IActionResult> SaveDocument(string documentId)
        {
            var userId = _userManager.GetUserId(User);  // Get current logged-in user's id

            // First, check if the document is already saved by the user
            var existingSavedDocument = await _context.UserSavedInfo
                .Where(u => u.UserId == userId && u.DocumentID == documentId)
                .FirstOrDefaultAsync();

            if (existingSavedDocument != null)
            {
                // Document is already saved
                //return Json(new { success = false, message = "文档已收藏" });

                // Document is already saved, so remove it
                _context.UserSavedInfo.Remove(existingSavedDocument);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "文档已移除收藏" , isFavorited = false}); // document removed from saved


            }

            var documentToSave = await _documentContext.Document
                .Include(d => d.University)
                .Include(d => d.Course)
                .Where(d => d.DocumentID == documentId)
                .FirstOrDefaultAsync();

            if (documentToSave == null)
            {
                // Document not found
                return Json(new { success = false, message = "未找到文档" });
            }

            var userSavedInfo = new UserSavedInfo
            {
                UserId = userId,
                DocumentID = documentToSave.DocumentID,
                DocumentName = documentToSave.Name,
                SchoolName=documentToSave.University.Name,
                CourseName=documentToSave.Course.CourseName
                
            };

            _context.UserSavedInfo.Add(userSavedInfo);
            await _context.SaveChangesAsync();

            return Json(new { success = true, message = "文档收藏成功" , isFavorited = true });
        }

    }
}

StudentFileShare6/Views/Course/CourseCreateSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>创造课程成功！</h1>

<a href="@Url.Content("/home/index")">返回首页</a>

StudentFileShare6/Views/Course/CourseView.cshtml
@model CourseViewModel

@{
    ViewData["Title"] = "CourseView";
}


<h1>@Model.CourseName</h1>
<h2>@Model.SchoolName</h2>


@*<form asp-action="SaveCourse" asp-controller="UserSavedInfo" method="post">
    <input type="hidden" name="courseId" value="@Model.CourseID" />
    <input type="submit" value="Save Course" />
</form>
*@

<button id="saveCourseBtn">收藏课程</button>

<table style="border-collapse: collapse; width: 100%;">
    <thead>
        <tr>
            <th class="border-cell">图片</th>
            <th class="border-cell">名称</th>
            <th class="border-cell">课程</th>
            <th class="border-cell">年份</th>
            <th class="border-cell">类别</th>
            <th class="border-cell">描述</th>
            <th class="border-cell">评分</th>
            <!-- Add other document properties as needed -->
        </tr>
    </thead>
    <tbody>
        @foreach (var document in Model.Documents)
        {
            var imageURL = (document.FirstPageImageLink ?? "").Replace("http:", "https:");
            <tr>
                <td class="border-cell"><img src="@imageURL" style="width: 200px; height: auto;" /></td>
                <td class="border-cell">
                    <a href="/Document/docview/@Model.SchoolName/@Model.CourseName/@document.Name/@document.DocumentID" target="_blank">
                        @document.Name
                    </a>
                </td>
                <td class="border-cell">@Model.CourseName</td>
                <td class="border-cell">@document.Year</td>
                <td class="border-cell">@document.Category</td>
                <td class="border-cell">@document.Description</td>
                <td class="border-cell">@document.Rating</td>
                <!-- Add other document properties as needed -->
            </tr>
        }
    </tbody>
</table>


@section Scripts {

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $("#saveCourseBtn").click(function () {
        @if (Context.User.Identity.IsAuthenticated)
        {
            <text>
                    $.ajax({
                        url: '@Url.Action("SaveCourse", "UserSavedInfo")',
                        type: 'POST',
                        data: { courseId: '@Model.CourseID' },
                        success: function (response) {
                            if (response.success) {
                                alert(response.message);
                            } else {
                                alert(response.message);
                            }

                            if (response.isFavorited) {
                                $('#saveCourseBtn').text('取消收藏课程');
                            } else {
                                $('#saveCourseBtn').text('收藏课程');
                            }
                        }
                    });
            </text>
        }
        else
        {
            <text>
                    alert('请先登录才能收藏');
            </text>
        }
            });
    </script>




    <script>

        $(document).ready(function () {
            // Make an AJAX request when the page loads
            $.ajax({
                url: '@Url.Action("IsCourseFavorited", "UserSavedInfo")',
                type: 'GET',
                data: { courseId: '@Model.CourseID' },
                success: function (response) {
                    if (response.isFavorited) {
                        $('#saveCourseBtn').text('取消收藏课程');
                    } else {
                        $('#saveCourseBtn').text('收藏课程');
                    }
                }
            });
        });

    </script>

}

StudentFileShare6/Views/Course/Create.cshtml
@model StudentFileShare6.Models.Course

@{
    ViewData["Title"] = "创建";
}

<h1>创建</h1>

<h4>课程</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group" style="display: none;">
                <label asp-for="CourseID" class="control-label"></label>
                <input asp-for="CourseID" class="form-control" value="DefaultCourseID" />
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label class="control-label">课程名称：</label>
                <input asp-for="CourseName" id="courseNameInput" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="SchoolID" class="control-label">请输入并选择学校名称：</label>
                <input type="text" id="schoolInput" class="form-control" autocomplete="off" list="universityList" />
                <datalist id="universityList"></datalist>
                <input type="hidden" asp-for="SchoolID" />
            </div>
            <a href="@Url.Content("/university/Create")">创建新的大学</a>

            <div class="form-group">
                <input type="submit" value="创建" id="submitButton" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-6 col-md-offset-2">
        <p>
            现有课程：
        </p>
        <p>
            <strong>上海大学：</strong>
            <br />
            <span>数据库</span>
            <br />
            <span>数学分析</span>
            <br />
        </p>
        <p>
            <strong>上海科技大学：</strong>
            <br />
            <span>物理</span>
            <br />
            <span>航空航天工程</span>
            <br />
        </p>
    </div>
</div>

@*<div>
    <a asp-action="Index">返回列表</a>
</div>*@

<a href="@Url.Content("/Document/Create")">返回上传文档</a>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        // For dynamic university input
        const inputElement = document.getElementById('schoolInput');
        const datalistElement = document.getElementById('universityList');
        const hiddenInput = document.querySelector('input[type="hidden"][name="SchoolID"]');


        inputElement.addEventListener('input', function () {
            const inputText = inputElement.value.trim();
            if (inputText.length === 0) {
                datalistElement.innerHTML = ''; // Clear the datalist if the input is empty
                return; // exit the function
            }

            //  console.log(inputText);   //works well
            getUniversities(inputText);

        });

       
    </script>

    <script>
        // If the user didn't select the right option when clicking the submit button, prevent form submission to keep the data they entered
        document.querySelector('input[type="submit"]').addEventListener('click', function (event) {
            var input = document.getElementById('schoolInput');
            var options = document.getElementById('universityList').options;
            var value = input.value;

            var match = Array.from(options).find(function (option) {
                return option.value === value;
            });

            if (!match) {
                event.preventDefault(); // Prevent form submission
                alert('请从列表中输入并选择大学名称。');
            } else {
                var courseNameInput = document.getElementById('courseNameInput').value;

                event.preventDefault(); // Prevents the form from submitting immediately

                fetch(`/Document/ifCourseExist?givenCourse=${courseNameInput}&SelectedSchoolID=${hiddenInput.value}`)
                    .then(function (response) {
                        return response.json();
                    })
                    .then(function (data) {
                        if (data.length > 0) {
                            alert('该课程在指定大学已存在。');
                        } else {
                            // Submit the form if the course doesn't exist
                            document.getElementById('courseNameInput').form.submit();
                        }
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
            }
        });
    </script>
}

StudentFileShare6/Views/Course/Delete.cshtml
@model StudentFileShare6.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Universities)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Universities.SchoolID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CourseID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StudentFileShare6/Views/Course/Details.cshtml
@model StudentFileShare6.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CourseName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CourseName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Universities)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Universities.SchoolID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CourseID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StudentFileShare6/Views/Course/Edit.cshtml
@model StudentFileShare6.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CourseID" />
            <div class="form-group">
                <label asp-for="CourseName" class="control-label"></label>
                <input asp-for="CourseName" class="form-control" />
                <span asp-validation-for="CourseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchoolID" class="control-label"></label>
                <select asp-for="SchoolID" class="form-control" asp-items="ViewBag.SchoolID"></select>
                <span asp-validation-for="SchoolID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StudentFileShare6/Views/Course/Index.cshtml
@model IEnumerable<StudentFileShare6.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CourseName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Universities)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Universities.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CourseID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CourseID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CourseID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>