StudentFileShare6/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudentFileShare6.data;
using StudentFileShare6.Models;
//using AliyunOss;
using Aliyun.OSS;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Net;
using Aliyun.OSS.Common;
using System.Security.AccessControl;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.Identity.Client;
using Microsoft.AspNetCore.SignalR;
using StudentFileShare6.Hubs;
using Microsoft.Extensions.Configuration;
using System.Configuration;
using System.Web;
using PdfiumViewer;
using System.Drawing;
using System.Drawing.Imaging;
using RestSharp;
using NPinyin;
using Spire.Doc;
using Spire.Presentation;
using Document = StudentFileShare6.Models.Document;
using DocumentSpire = Spire.Doc;
using FileFormat = Spire.Presentation.FileFormat;
using System.Diagnostics;

namespace StudentFileShare6.Controllers
{
    public class DocumentController : Controller
    {
        private readonly DocumentContext _context;
        private readonly IHubContext<ProgressHub> _hubContext;
        private readonly UniversityContext _universityContext;
        private readonly CourseContext _courseContext;
        private readonly IConfiguration _configuration;


        public DocumentController(IConfiguration configuration, DocumentContext context, IHubContext<ProgressHub> hubContext, CourseContext courseContext, UniversityContext universityContext)
        {
            _context = context;
            _hubContext = hubContext;

            _courseContext = courseContext;
            _universityContext = universityContext;
            _configuration = configuration;
        }

        // GET: Document
        public async Task<IActionResult> Index()
        {
            var documentContext = _context.Document.Include(d => d.Course).Include(d => d.University);
            var documents = await documentContext.ToListAsync();

            // Fetch the base64-encoded image for each document and add it to the ViewData dictionary
            foreach (var document in documents)
            {
                string imageUrl = document.FirstPageImageLink;
                ViewData[document.DocumentID.ToString()] = imageUrl;
            }

            return View(documents);
        }
        // GET: Document/UserUploadedDocumentsPage
        public async Task<IActionResult> UserUploadedDocumentsPage()
        {
            var documentContext = _context.Document.Include(d => d.Course).Include(d => d.University);
            var documents = await documentContext.ToListAsync();

            // Fetch the base64-encoded image for each document and add it to the ViewData dictionary
            foreach (var document in documents)
            {
                string imageUrl = document.FirstPageImageLink;
                ViewData[document.DocumentID.ToString()] = imageUrl;
            }

            return View(documents);
        }

        // GET: Document/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Document == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .Include(d => d.Course)
                .Include(d => d.University)
                .FirstOrDefaultAsync(m => m.DocumentID == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Document/Create
        public IActionResult Create()
        {
            var document = new Document();
            return View(document);
        }

        [HttpGet]
        public IActionResult GetUniversities(string searchText)
        {
            //the GetUniversities function is not directly called in the Create.cshtml file. Instead, it is called asynchronously from JavaScript code using the fetch API
            List<University> universities = _universityContext.Universities.ToList();
            var matchingUniversities = universities
                 .Where(u => ((u.Name)).StartsWith(searchText))
                 //  .Where(u => ((u.Name).ToLower()).Contains(searchText.ToLower()))
                 //  we want if user enter small case it can match what we got in the database
                 .Select(u => new { Name = u.Name, SchoolID = u.SchoolID, Location = u.Location })
                 .Take(10)
                 .ToList();
            //When using var, we declare implicit type variables, the compiler infers the variable’s type from its value automatically
            return Json(matchingUniversities);
        }

        [HttpGet]
        public IActionResult GetCourses(string searchText, string SelectedSchoolID)
        {
            //the GetUniversities function is not directly called in the Create.cshtml file. Instead, it is called asynchronously from JavaScript code using the fetch API
            List<Course> courses = _courseContext.Course.ToList();
            var matchingCourses = courses
                  .Where(u => ((u.CourseName)).StartsWith(searchText) && u.SchoolID == SelectedSchoolID)
                  //.Where(u => ((u.CourseName).ToLower()).Contains(searchText.ToLower()) && u.SchoolID == SelectedSchoolID)
                  .Select(u => new { Name = u.CourseName, CourseID = u.CourseID })
                  .Take(10)
                  .ToList();
            //When using var, we declare implicit type variables, the compiler infers the variable’s type from its value automatically
            return Json(matchingCourses);
        }





        [HttpGet]
        public IActionResult ifUniversityExist(string givenName, string givenLocation)
        //To prevent the user from submitting the form if the university name already exists in the database
        {
            List<University> universities = _universityContext.Universities.ToList();
            var matchingUniversities = universities
                 .Where(u => u.Name== givenName && u.Location == givenLocation)
                 .Select(u => new { Name = u.Name, SchoolID = u.SchoolID, Location = u.Location })
                 .Take(10)
                 .ToList();

            return Json(matchingUniversities);
        }


        [HttpGet]
        public IActionResult ifCourseExist(string givenCourse, string SelectedSchoolID)
        {
            //the GetUniversities function is not directly called in the Create.cshtml file. Instead, it is called asynchronously from JavaScript code using the fetch API
            List<Course> courses = _courseContext.Course.ToList();
            var matchingCourses = courses
                  .Where(u => ((u.CourseName)).StartsWith(givenCourse) && u.SchoolID.ToLower() == SelectedSchoolID.ToLower())
                  //.Where(u => ((u.CourseName).ToLower()).Contains(searchText.ToLower()) && u.SchoolID == SelectedSchoolID)
                  .Select(u => new { Name = u.CourseName, CourseID = u.CourseID })
                  .Take(10)
                  .ToList();
            //When using var, we declare implicit type variables, the compiler infers the variable’s type from its value automatically
            return Json(matchingCourses);
        }

        // POST: Document/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DocumentID,Name,SchoolID,CourseID,Year,Category,Description,Anonymous,UserID,Link")] Document document, IFormFile file)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    // Log validation errors
                    foreach (var modelStateEntry in ModelState.Values)
                    {
                        foreach (var error in modelStateEntry.Errors)
                        {
                            System.Diagnostics.Debug.WriteLine(error.ErrorMessage);
                        }
                    }

                    return View(document);
                }




                if (ModelState.IsValid)
                {


                    document.GenerateRandomDocumentID(_context);

                    if (file != null && file.Length > 0)
                    {




                        //    var configuration = new ConfigurationBuilder()
                        //.SetBasePath(Directory.GetCurrentDirectory())
                        //.AddJsonFile("appsettings.json")
                        //.Build();

                        var accessKeyId = _configuration["CloudOSSConnection:accessKeyId"];


                        var accessKeySecret = _configuration["CloudOSSConnection:accessKeySecret"];
                        var endpoint = _configuration["CloudOSSConnection:endpoint"];
                        var bucketName = _configuration["CloudOSSConnection:bucketName"];
                        var bucketForFirstPagePdf = _configuration["CloudOSSConnection:bucketNameForFirstPagePdf"];

                        // because for OSS, if you upload an object that has the same name as an existing object, the existing object is overwritten by the uploaded object
                        //another method see https://www.alibabacloud.com/help/en/object-storage-service/latest/disable-overwrite-for-objects-with-the-same-name-3
                        string fileName = Path.GetFileName(file.FileName);  // assuming fileName is "example.txt"

                        string fileExtension = Path.GetExtension(fileName);

                        string UploadfileName;

                        switch (fileExtension)
                        {
                            case ".pdf":

StudentFileShare6/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Microsoft.EntityFrameworkCore;
using StudentFileShare6.data;
using StudentFileShare6.Models;

namespace StudentFileShare6.Controllers
{
    public class SearchController : Controller
    {
        private readonly DocumentContext _context;

        private readonly UniversityContext _universityContext;
        private readonly CourseContext _courseContext;

        public SearchController(DocumentContext context, CourseContext courseContext, UniversityContext universityContext)
        {
            _context = context;
            _courseContext = courseContext;
            _universityContext = universityContext;
        }


        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Search(string SchoolID, string CourseID, string textInput)
        //we can use form in cshtml specify this method, so it is not called directly, for example
        //<form id="searchDocumentForm" asp-action="Search" enctype="multipart/form-data">
        //but if we want to update dynamically each time we click then we cannot use this, we need to use javascript etc
        {


            //    When using var, we declare implicit type variables, the compiler infers the variable’s type from its value automatically

            var searchResults = _context.Document
    .Where(d => d.Name.Contains(textInput) && d.SchoolID == SchoolID && d.CourseID == CourseID)
    .Select(d => new
    {
        d.Name,
        d.DocumentID,
        CourseName = d.Course.CourseName, // Include only CourseName and assign it to Name property
        UniversityName=d.University.Name,   //cannot use     .Include(d => d.University)    because won't work in Json
        UniversityLocation= d.University.Location,
        d.SchoolID,
        d.CourseID,
        d.Year,
        d.Category,
        d.Description,
        d.Rating,

        d.Anonymous,
        d.UserID,
        d.Link,
        d.FirstPageImageLink,
        d.University
    })
    .ToList();


            return Json(searchResults);
        }

       





    }
}

StudentFileShare6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 学生文件分享网站</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentFileShare6.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">学习文件分享（演示)</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">首页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">隐私政策</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">搜索文件</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Document" asp-action="Create">上传文件</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_loginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - 学生文件分享 - <a asp-area="" asp-controller="Home" asp-action="Privacy">隐私政策</a>
            <a asp-area="" asp-controller="Home" asp-action="AboutUs">关于我们</a>

            <a asp-area="" asp-controller="Home" asp-action="AcademicIntegrity">学术诚信</a>

            <a asp-area="" asp-controller="Home" asp-action="Contact">联系我们</a>

            <a asp-area="" asp-controller="Home" asp-action="CookieStatement">Cookie 声明</a>

            <a asp-area="" asp-controller="Home" asp-action="Jobs">空缺职位</a>

            <a asp-area="" asp-controller="Home" asp-action="News">新闻</a>

            <a asp-area="" asp-controller="Home" asp-action="Terms">条款</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>